# Notes
# a step cannot have both the `uses` and `run` keys


name: Actions Workflow

on: 
  schedule:     # Schedule this job to run on specified cron 
    - cron: "0/5 * * * *"
    - cron: "0/6 * * * *"
  pull_request:
    types: [closed, assigned, reopened, opened]   ## Specify the types of pull requests to run this job

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"

      - name: Simple JS Action
        id: greet # To reference the step in the steps variable.   
        uses:  actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Ahsan # Input parameter
      
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"   # Get the output of the step using the steps variable